### ISSUE TITLE
Only adds 1 month at a time. 

### ISSUE THREAD

**Issue by ChiefMedicalOfficer** [nonPointer/Glasgow-Bin-Collection-iCal#1]
Amazing idea and it's exactly what I'm looking for. Only thing is it is only adding the current month to the calendar.

It's possible I'm being stupid or is that by design.

Thanks again.

**Comment by nonPointer** [comment]
Hi @ChiefMedicalOfficer , I am surprised that this utility tool can help you. Unfortunately, I don't know much JavaScript so I failed to port the yearly calendar. This project is based on regex match, which is simpler than parsing the HTML DOM.
If you want full-year view, please look at `https://www.glasgow.gov.uk/forms/refuseandrecyclingcalendar/PrintCalendar.aspx?UPRN=[UPRN]`.
Many thanks!

**Comment by ChiefMedicalOfficer** [comment]
Amazing man. I'll get on that tonight. Thanks again.

**Comment by nonPointer** [comment]
Please try [this](https://github.com/nonPointer/Glasgow-Bin-Collection-iCal-Py)

**Comment by ChiefMedicalOfficer** [comment]
> Please try [this](https://github.com/nonPointer/Glasgow-Bin-Collection-iCal-Py)

I'll try this out tonight. Thanks again.

**Comment by ChiefMedicalOfficer** [comment]
> Please try [this](https://github.com/nonPointer/Glasgow-Bin-Collection-iCal-Py)

Aw mate sorry I forgot to reply. It all works great now.
